name: A workflow for my Evalucacion de Backend de Luis
on: push

jobs:
  build:
    name: Run the Evalucacion de Backend de Luis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./hello-world
        with:
          N_INDEX: 12

